language: php

php:
  - 5.5
  - 5.6
  - hhvm

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --prefer-source --dev --no-interaction

script:
  - php vendor/bin/phpcs ./src --standard=PSR1 --encoding=utf-8
  - php vendor/bin/phpcs ./src --standard=PSR2 --encoding=utf-8
  - php vendor/bin/phpunit --verbose --coverage-clover=.reports/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

branches:
  only:
    - develop

notifications:
  email: "baleyko@gmail.com"
